version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase..."
      - cd wanderwise-app/
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - cd wanderwise-app/

  build:
    commands:
      - echo "Building the project..."
      - cd wanderwise-app/
      - npm run build

artifacts:
  base-directory: wanderwise-app/.next #
  files:
    - "**/*"

cache:
  paths:
    - wanderwise-app/node_modules/**/*
