//file to hold dummy data for the different

export const flightsPlaceholder = {
  meta: {
    count: 2,
    links: {
      self: "https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=LAX&destinationLocationCode=PAR&departureDate=2024-06-01&returnDate=2024-06-10&adults=1&children=0&infants=0&travelClass=ECONOMY&nonStop=true&max=10",
    },
  },
  data: [
    {
      type: "flight-offer",
      id: "1",
      source: "GDS",
      instantTicketingRequired: false,
      nonHomogeneous: false,
      oneWay: false,
      lastTicketingDate: "2024-05-28",
      lastTicketingDateTime: "2024-05-28",
      numberOfBookableSeats: 9,
      itineraries: [
        {
          duration: "PT10H50M",
          segments: [
            {
              departure: {
                iataCode: "LAX",
                terminal: "B",
                at: "2024-06-01T19:45:00",
              },
              arrival: {
                iataCode: "ORY",
                terminal: "4",
                at: "2024-06-02T15:35:00",
              },
              carrierCode: "BF",
              number: "731",
              aircraft: {
                code: "359",
              },
              operating: {
                carrierCode: "BF",
              },
              duration: "PT10H50M",
              id: "2",
              numberOfStops: 0,
              blacklistedInEU: false,
            },
          ],
        },
        {
          duration: "PT11H40M",
          segments: [
            {
              departure: {
                iataCode: "ORY",
                terminal: "4",
                at: "2024-06-10T14:50:00",
              },
              arrival: {
                iataCode: "LAX",
                terminal: "B",
                at: "2024-06-10T17:30:00",
              },
              carrierCode: "BF",
              number: "730",
              aircraft: {
                code: "359",
              },
              operating: {
                carrierCode: "BF",
              },
              duration: "PT11H40M",
              id: "10",
              numberOfStops: 0,
              blacklistedInEU: false,
            },
          ],
        },
      ],
      price: {
        currency: "EUR",
        total: "847.20",
        base: "461.00",
        fees: [
          {
            amount: "0.00",
            type: "SUPPLIER",
          },
          {
            amount: "0.00",
            type: "TICKETING",
          },
        ],
        grandTotal: "847.20",
        additionalServices: [
          {
            amount: "120.00",
            type: "CHECKED_BAGS",
          },
        ],
      },
      pricingOptions: {
        fareType: ["PUBLISHED"],
        includedCheckedBagsOnly: false,
      },
      validatingAirlineCodes: ["BF"],
      travelerPricings: [
        {
          travelerId: "1",
          fareOption: "STANDARD",
          travelerType: "ADULT",
          price: {
            currency: "EUR",
            total: "847.20",
            base: "461.00",
          },
          fareDetailsBySegment: [
            {
              segmentId: "2",
              cabin: "ECONOMY",
              fareBasis: "QBCRTUS",
              brandedFare: "BASICPLUS",
              brandedFareLabel: "BASIC PLUS",
              class: "Q",
              includedCheckedBags: {
                quantity: 0,
              },
              amenities: [
                {
                  description: "CHECKED BAG SECOND",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHECKED BAG THIRD",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "FIRST BAG",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "PRE RESERVED SEAT ASSIGNMENT",
                  isChargeable: true,
                  amenityType: "PRE_RESERVED_SEAT",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "BASIC MEAL",
                  isChargeable: false,
                  amenityType: "MEAL",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHANGE BEFORE DEPARTURE",
                  isChargeable: true,
                  amenityType: "BRANDED_FARES",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHANGE AFTER DEPARTURE",
                  isChargeable: true,
                  amenityType: "BRANDED_FARES",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
              ],
            },
            {
              segmentId: "10",
              cabin: "ECONOMY",
              fareBasis: "QBCRTUS",
              brandedFare: "BASICPLUS",
              brandedFareLabel: "BASIC PLUS",
              class: "Q",
              includedCheckedBags: {
                quantity: 0,
              },
              amenities: [
                {
                  description: "CHECKED BAG SECOND",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHECKED BAG THIRD",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "FIRST BAG",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "PRE RESERVED SEAT ASSIGNMENT",
                  isChargeable: true,
                  amenityType: "PRE_RESERVED_SEAT",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "BASIC MEAL",
                  isChargeable: false,
                  amenityType: "MEAL",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHANGE BEFORE DEPARTURE",
                  isChargeable: true,
                  amenityType: "BRANDED_FARES",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHANGE AFTER DEPARTURE",
                  isChargeable: true,
                  amenityType: "BRANDED_FARES",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "flight-offer",
      id: "2",
      source: "GDS",
      instantTicketingRequired: false,
      nonHomogeneous: false,
      oneWay: false,
      lastTicketingDate: "2024-05-28",
      lastTicketingDateTime: "2024-05-28",
      numberOfBookableSeats: 9,
      itineraries: [
        {
          duration: "PT10H50M",
          segments: [
            {
              departure: {
                iataCode: "LAX",
                terminal: "B",
                at: "2024-06-01T19:45:00",
              },
              arrival: {
                iataCode: "ORY",
                terminal: "4",
                at: "2024-06-02T15:35:00",
              },
              carrierCode: "TX",
              number: "6731",
              aircraft: {
                code: "359",
              },
              operating: {
                carrierCode: "BF",
              },
              duration: "PT10H50M",
              id: "3",
              numberOfStops: 0,
              blacklistedInEU: false,
            },
          ],
        },
        {
          duration: "PT11H40M",
          segments: [
            {
              departure: {
                iataCode: "ORY",
                terminal: "4",
                at: "2024-06-10T14:50:00",
              },
              arrival: {
                iataCode: "LAX",
                terminal: "B",
                at: "2024-06-10T17:30:00",
              },
              carrierCode: "TX",
              number: "6730",
              aircraft: {
                code: "359",
              },
              operating: {
                carrierCode: "BF",
              },
              duration: "PT11H40M",
              id: "11",
              numberOfStops: 0,
              blacklistedInEU: false,
            },
          ],
        },
      ],
      price: {
        currency: "EUR",
        total: "847.20",
        base: "461.00",
        fees: [
          {
            amount: "0.00",
            type: "SUPPLIER",
          },
          {
            amount: "0.00",
            type: "TICKETING",
          },
        ],
        grandTotal: "847.20",
        additionalServices: [
          {
            amount: "150.00",
            type: "CHECKED_BAGS",
          },
        ],
      },
      pricingOptions: {
        fareType: ["PUBLISHED"],
        includedCheckedBagsOnly: false,
      },
      validatingAirlineCodes: ["TX"],
      travelerPricings: [
        {
          travelerId: "1",
          fareOption: "STANDARD",
          travelerType: "ADULT",
          price: {
            currency: "EUR",
            total: "847.20",
            base: "461.00",
          },
          fareDetailsBySegment: [
            {
              segmentId: "3",
              cabin: "ECONOMY",
              fareBasis: "TBCRTUS",
              brandedFare: "EBASIC",
              brandedFareLabel: "ECO BASIC",
              class: "T",
              includedCheckedBags: {
                quantity: 0,
              },
              amenities: [
                {
                  description: "CHECKED BAG FIRST",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHECKED BAG SECOND",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHECKED BAG THIRD",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "BAGGAGE DELIVERY AIRPORT",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "PRE RESERVED SEAT ASSIGNMENT",
                  isChargeable: true,
                  amenityType: "PRE_RESERVED_SEAT",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "MEAL",
                  isChargeable: false,
                  amenityType: "MEAL",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "TEENAGER MEAL",
                  isChargeable: true,
                  amenityType: "MEAL",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
              ],
            },
            {
              segmentId: "11",
              cabin: "ECONOMY",
              fareBasis: "TBCRTUS",
              brandedFare: "EBASIC",
              brandedFareLabel: "ECO BASIC",
              class: "T",
              includedCheckedBags: {
                quantity: 0,
              },
              amenities: [
                {
                  description: "CHECKED BAG FIRST",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHECKED BAG SECOND",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "CHECKED BAG THIRD",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "BAGGAGE DELIVERY AIRPORT",
                  isChargeable: true,
                  amenityType: "BAGGAGE",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "PRE RESERVED SEAT ASSIGNMENT",
                  isChargeable: true,
                  amenityType: "PRE_RESERVED_SEAT",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "MEAL",
                  isChargeable: false,
                  amenityType: "MEAL",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
                {
                  description: "TEENAGER MEAL",
                  isChargeable: true,
                  amenityType: "MEAL",
                  amenityProvider: {
                    name: "BrandedFare",
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

export const singleFlight = {
  type: "flight-offer",
  id: "1",
  source: "GDS",
  instantTicketingRequired: false,
  nonHomogeneous: false,
  oneWay: false,
  lastTicketingDate: "2024-05-28",
  lastTicketingDateTime: "2024-05-28",
  numberOfBookableSeats: 9,
  itineraries: [
    {
      duration: "PT10H50M",
      segments: [
        {
          departure: {
            iataCode: "LAX",
            terminal: "B",
            at: "2024-06-01T19:45:00",
          },
          arrival: {
            iataCode: "ORY",
            terminal: "4",
            at: "2024-06-02T15:35:00",
          },
          carrierCode: "BF",
          number: "731",
          aircraft: {
            code: "359",
          },
          operating: {
            carrierCode: "BF",
          },
          duration: "PT10H50M",
          id: "2",
          numberOfStops: 0,
          blacklistedInEU: false,
        },
      ],
    },
    {
      duration: "PT11H40M",
      segments: [
        {
          departure: {
            iataCode: "ORY",
            terminal: "4",
            at: "2024-06-10T14:50:00",
          },
          arrival: {
            iataCode: "LAX",
            terminal: "B",
            at: "2024-06-10T17:30:00",
          },
          carrierCode: "BF",
          number: "730",
          aircraft: {
            code: "359",
          },
          operating: {
            carrierCode: "BF",
          },
          duration: "PT11H40M",
          id: "10",
          numberOfStops: 0,
          blacklistedInEU: false,
        },
      ],
    },
  ],
  price: {
    currency: "EUR",
    total: "847.20",
    base: "461.00",
    fees: [
      {
        amount: "0.00",
        type: "SUPPLIER",
      },
      {
        amount: "0.00",
        type: "TICKETING",
      },
    ],
    grandTotal: "847.20",
    additionalServices: [
      {
        amount: "120.00",
        type: "CHECKED_BAGS",
      },
    ],
  },
  pricingOptions: {
    fareType: ["PUBLISHED"],
    includedCheckedBagsOnly: false,
  },
  validatingAirlineCodes: ["BF"],
  travelerPricings: [
    {
      travelerId: "1",
      fareOption: "STANDARD",
      travelerType: "ADULT",
      price: {
        currency: "EUR",
        total: "847.20",
        base: "461.00",
      },
      fareDetailsBySegment: [
        {
          segmentId: "2",
          cabin: "ECONOMY",
          fareBasis: "QBCRTUS",
          brandedFare: "BASICPLUS",
          brandedFareLabel: "BASIC PLUS",
          class: "Q",
          includedCheckedBags: {
            quantity: 0,
          },
          amenities: [
            {
              description: "CHECKED BAG SECOND",
              isChargeable: true,
              amenityType: "BAGGAGE",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "CHECKED BAG THIRD",
              isChargeable: true,
              amenityType: "BAGGAGE",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "FIRST BAG",
              isChargeable: true,
              amenityType: "BAGGAGE",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "PRE RESERVED SEAT ASSIGNMENT",
              isChargeable: true,
              amenityType: "PRE_RESERVED_SEAT",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "BASIC MEAL",
              isChargeable: false,
              amenityType: "MEAL",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "CHANGE BEFORE DEPARTURE",
              isChargeable: true,
              amenityType: "BRANDED_FARES",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "CHANGE AFTER DEPARTURE",
              isChargeable: true,
              amenityType: "BRANDED_FARES",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
          ],
        },
        {
          segmentId: "10",
          cabin: "ECONOMY",
          fareBasis: "QBCRTUS",
          brandedFare: "BASICPLUS",
          brandedFareLabel: "BASIC PLUS",
          class: "Q",
          includedCheckedBags: {
            quantity: 0,
          },
          amenities: [
            {
              description: "CHECKED BAG SECOND",
              isChargeable: true,
              amenityType: "BAGGAGE",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "CHECKED BAG THIRD",
              isChargeable: true,
              amenityType: "BAGGAGE",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "FIRST BAG",
              isChargeable: true,
              amenityType: "BAGGAGE",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "PRE RESERVED SEAT ASSIGNMENT",
              isChargeable: true,
              amenityType: "PRE_RESERVED_SEAT",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "BASIC MEAL",
              isChargeable: false,
              amenityType: "MEAL",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "CHANGE BEFORE DEPARTURE",
              isChargeable: true,
              amenityType: "BRANDED_FARES",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
            {
              description: "CHANGE AFTER DEPARTURE",
              isChargeable: true,
              amenityType: "BRANDED_FARES",
              amenityProvider: {
                name: "BrandedFare",
              },
            },
          ],
        },
      ],
    },
  ],
};

export const tripCardData = [
  {
    id: "2",
    start_date: "2024-06-15",
    end_date: "2024-06-21",
    flight_booked: false,
    hotel_booked: true,
    destination_city: "Maniila",
    destination_country: "Philippines",
    updated_at: "2024-06-06 @ 23:09",
  },
  {
    id: "3",
    start_date: "2024-06-15",
    end_date: "2024-06-21",
    flight_booked: false,
    hotel_booked: true,
    destination_city: "Lover Land",
    destination_country: "Philippines",
    updated_at: "2024-06-06 @ 23:09",
  },
];

export const tripAdvisorAttractions = {
  data: [
    {
      location_id: "151972",
      name: "Bahia de Los Angeles",
      address_obj: {
        street1: "",
        street2: "",
        city: "Bahia de Los Angeles",
        state: "Baja California Norte",
        country: "Mexico",
        postalcode: "22890",
        address_string:
          "Bahia de Los Angeles, Ensenada Municipality 22890 Mexico",
      },
    },
    {
      location_id: "560853",
      name: "Los Angeles Convention Center",
      address_obj: {
        street1: "1201 S Figueroa St",
        street2: "",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90015-1308",
        address_string: "1201 S Figueroa St, Los Angeles, CA 90015-1308",
      },
    },
    {
      location_id: "491889",
      name: "Metro Los Angeles",
      address_obj: {
        street1: "1 Gateway Plaza",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90012-3745",
        address_string: "1 Gateway Plaza, Los Angeles, CA 90012-3745",
      },
    },
    {
      location_id: "106166",
      name: "Los Angeles County Museum of Art",
      address_obj: {
        street1: "5905 Wilshire Blvd",
        street2: "",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90036-4597",
        address_string: "5905 Wilshire Blvd, Los Angeles, CA 90036-4597",
      },
    },
    {
      location_id: "560855",
      name: "Los Angeles Memorial Coliseum",
      address_obj: {
        street1: "3911 S Figueroa St",
        street2: "Exposition Park",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90037-1207",
        address_string:
          "3911 S Figueroa St Exposition Park, Los Angeles, CA 90037-1207",
      },
    },
    {
      location_id: "144145",
      name: "University of California, Los Angeles (UCLA)",
      address_obj: {
        street1: "Sunset Blvd.",
        street2: "",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "",
        address_string: "Sunset Blvd., Los Angeles, CA",
      },
    },
    {
      location_id: "15084575",
      name: "The Port of Los Angeles",
      address_obj: {
        street1: "425 South Palos Verdes Street",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90731",
        address_string: "425 South Palos Verdes Street, Los Angeles, CA 90731",
      },
    },
    {
      location_id: "8399942",
      name: "Los Angeles Termal",
      address_obj: {
        street1: "Vereda Agua Caliente",
        city: "Rivera",
        country: "Colombia",
        address_string: "Vereda Agua Caliente, Rivera Colombia",
      },
    },
    {
      location_id: "116885",
      name: "Los Angeles Zoo & Botanical Gardens",
      address_obj: {
        street1: "5333 Zoo Dr",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90027-1451",
        address_string: "5333 Zoo Dr, Los Angeles, CA 90027-1451",
      },
    },
    {
      location_id: "143621",
      name: "Los Angeles Central Library",
      address_obj: {
        street1: "630 W 5th St",
        city: "Los Angeles",
        state: "California",
        country: "United States",
        postalcode: "90071-2002",
        address_string: "630 W 5th St, Los Angeles, CA 90071-2002",
      },
    },
  ],
};

export const conventionCenter = [
  {
    location_id: "560853",
    name: "Los Angeles Convention Center",
    description:
      "The Los Angeles Convention Center attracts millions of visitors annually and is renowned internationally as a prime site for conventions, trade shows, and exhibitions. Located in the cultural, business, and entertainment mecca of Downtown Los Angeles, the LACC is an integral economic component of the Southern California area, and remains an enduring symbol of environmental sustainability and social responsibility for our community. First opened to the public in 1971, the LACC has since undergone modernization and expansion; as a testament to our continuous effort to enhance our facility and services, the LACC is embarking on its fourth phase of renovation under AEG’s management this year. The year-long transformation will enhance both functionality and aesthetics of the LACC, and will include replacing existing carpet, installing the latest energy-efficient products such as “cool roofs” and new air handling units, completely remodeling the theatre, and upgrading IT infrastructure and operating systems throughout the Center.",
    web_url:
      "https://www.tripadvisor.com/Attraction_Review-g32655-d560853-Reviews-Los_Angeles_Convention_Center-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "1201 S Figueroa St",
      street2: "",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90015-1308",
      address_string: "1201 S Figueroa St, Los Angeles, CA 90015-1308",
    },
    ancestors: [
      {
        level: "City",
        name: "Los Angeles",
        location_id: "32655",
      },
      {
        abbrv: "CA",
        level: "State",
        name: "California",
        location_id: "28926",
      },
      {
        level: "Country",
        name: "United States",
        location_id: "191",
      },
    ],
    latitude: "34.04297",
    longitude: "-118.26955",
    timezone: "America/Los_Angeles",
    phone: "+1 213-741-1151",
    website: "http://www.lacclink.com",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d560853-Los_Angeles_Convention_Center-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#83 of 926 things to do in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "926",
      ranking: "83",
    },
    rating: "4.0",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-66827-5.svg",
    num_reviews: "227",
    review_rating_count: {
      1: "8",
      2: "6",
      3: "43",
      4: "78",
      5: "92",
    },
    photo_count: "199",
    see_all_photos:
      "https://www.tripadvisor.com/Attraction_Review-g32655-d560853-m66827-Reviews-Los_Angeles_Convention_Center-Los_Angeles_California.html#photos",
    hours: {
      periods: [
        {
          open: { day: 1, time: "0800" },
          close: { day: 1, time: "1700" },
        },
        {
          open: { day: 2, time: "0800" },
          close: { day: 2, time: "1700" },
        },
        {
          open: { day: 3, time: "0800" },
          close: { day: 3, time: "1700" },
        },
        {
          open: { day: 4, time: "0800" },
          close: { day: 4, time: "1700" },
        },
        {
          open: { day: 5, time: "0800" },
          close: { day: 5, time: "1700" },
        },
        {
          open: { day: 6, time: "0800" },
          close: { day: 6, time: "1700" },
        },
        {
          open: { day: 7, time: "0800" },
          close: { day: 7, time: "1700" },
        },
      ],
      weekday_text: [
        "Monday: 08:00 - 17:00",
        "Tuesday: 08:00 - 17:00",
        "Wednesday: 08:00 - 17:00",
        "Thursday: 08:00 - 17:00",
        "Friday: 08:00 - 17:00",
        "Saturday: 08:00 - 17:00",
        "Sunday: 08:00 - 17:00",
      ],
    },
    category: {
      name: "attraction",
      localized_name: "Attraction",
    },
    subcategory: [
      {
        name: "traveler_resources",
        localized_name: "Traveler Resources",
      },
      {
        name: "attractions",
        localized_name: "Attractions",
      },
    ],
    groups: [
      {
        name: "Traveler Resources",
        localized_name: "Traveler Resources",
        categories: [
          {
            name: "Conference & Convention Centers",
            localized_name: "Conference & Convention Centers",
          },
        ],
      },
    ],
    neighborhood_info: [
      {
        location_id: "7231034",
        name: "Downtown",
      },
      {
        location_id: "20933761",
        name: "Central L.A",
      },
    ],
    trip_types: [
      {
        name: "business",
        localized_name: "Business",
        value: "83",
      },
      {
        name: "couples",
        localized_name: "Couples",
        value: "19",
      },
      {
        name: "solo",
        localized_name: "Solo travel",
        value: "20",
      },
      {
        name: "family",
        localized_name: "Family",
        value: "28",
      },
      {
        name: "friends",
        localized_name: "Friends getaway",
        value: "23",
      },
    ],
    awards: [],
  },
];

export const hotels = [
  {
    location_id: "23845025",
    name: "Conrad Los Angeles",
    description:
      "Daily Mandatory Charge includes: Destination Charge with premium internet access; daily $15 food and beverage credit; house car use; Conrad Spa dry sauna & tea blending bar; in-lobby premium coffee; RunGo app access for trails; PressReader. Mandatory Charge also includes CA & LA Tourism Assessments. Surrounded by iconic art, theatre, and music institutions, Conrad Los Angeles channels the bold originality, creative innovation and dynamic energy that fuels Downtown LA's newest cultural corridor. Heralded by the vision of legendary architect Frank Gehry, our hotel is an elegant destination for vibrant social events, remarkable gatherings and curated dining experiences by acclaimed chef and humanitarian Jose Andres. Here, framed by dramatic views of the Walt Disney Concert Hall and Downtown LA, discover energizing experiences that will ignite your inspiration.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d23845025-Reviews-Conrad_Los_Angeles-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "100 South Grand Ave.",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90012",
      address_string: "100 South Grand Ave., Los Angeles, CA 90012",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.055176",
    longitude: "-118.24858",
    timezone: "America/Los_Angeles",
    phone: "18556184701",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d23845025-Conrad_Los_Angeles-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#63 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "63",
    },
    rating: "4.5",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-66827-5.svg",
    num_reviews: "144",
    review_rating_count: { 1: "7", 2: "10", 3: "5", 4: "6", 5: "116" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "672",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d23845025-m66827-Reviews-Conrad_Los_Angeles-Los_Angeles_California.html#photos",
    price_level: "$$$$",
    amenities: [
      "Pool",
      "Internet",
      "Suites",
      "Room service",
      "Free Internet",
      "Wheelchair access",
      "Restaurant",
      "Spa",
      "Wifi",
      "Free Wifi",
      "Dry Cleaning",
      "Meeting rooms",
      "Non-smoking rooms",
      "Business center",
      "Fitness center",
      "Laundry Service",
      "Concierge",
      "Electric vehicle charging station",
      "English",
      "Pool with View",
      "Spanish",
      "Kids Activities",
      "Bar/Lounge",
      "Pets Allowed",
      "Banquet Room",
      "Air conditioning",
      "Accessible rooms",
      "Minibar",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Rooftop Pool",
      "Heated pool",
      "Flatscreen TV",
      "Rooftop Terrace",
      "Poolside Bar",
      "Outdoor pool",
      "Breakfast Available",
      "Facilities for Disabled Guests",
      "Housekeeping",
      "Sauna",
      "Baggage Storage",
      "Bathrobes",
      "Blackout Curtains",
      "Body Wrap",
      "Bottled Water",
      "Breakfast in the Room",
      "Cable / Satellite TV",
      "Children's Television Networks",
      "Clothes Rack",
      "Couples Massage",
      "Desk",
      "Facial Treatments",
      "Fitness Classes",
      "Fitness / Spa Locker Rooms",
      "Complimentary Toiletries",
      "24-Hour Front Desk",
      "Full Body Massage",
      "Hair Dryer",
      "Happy Hour",
      "Highchairs Available",
      "Iron",
      "Kids' Meals",
      "Landmark View",
      "Light Therapy",
      "Massage",
      "Mountain View",
      "Newspaper",
      "Outdoor Dining Area",
      "Outdoor Fireplace",
      "Outdoor Furniture",
      "Patio",
      "Pool / Beach Towels",
      "Pool View",
      "Private Bathrooms",
      "Paid Private Parking On-site",
      "Seating Area",
      "24-Hour Security",
      "Secured Parking",
      "Shoeshine",
      "Shops",
      "Sofa",
      "Steam Room",
      "Sun Deck",
      "Sun Loungers / Beach Chairs",
      "Sun Terrace",
      "Sun Umbrellas",
      "Telephone",
      "Valet Parking",
      "Wake Up Service / Alarm Clock",
      "Walk-in Shower",
      "Walking Tours",
      "Wardrobe / Closet",
      "Wine / Champagne",
      "Yoga Classes",
    ],
    parent_brand: "Hilton Worldwide",
    brand: "Conrad Hotels & Resorts",
    category: { name: "hotel", localized_name: "Hotel" },
    subcategory: [[Object]],
    styles: ["Luxury", "Romantic"],
    neighborhood_info: [],
    trip_types: [[Object], [Object], [Object], [Object], [Object]],
    awards: [[Object]],
  },
  {
    location_id: "77798",
    name: "Sheraton Grand Los Angeles",
    description:
      "Thrive brimming with style and substance at Sheraton Grand Los Angeles. Head to District Kitchen & Bar, our innovative on-site restaurant serving creative libations and farm-to-table cuisine. Work and play like a Los Angeleno at our fully equipped Sheraton Fitness center. If you are planning a professional meeting, special event, or a lavish wedding, ask about our indoor and outdoor event venues offering more than 35,000 square feet of space. After a busy day in DTLA, unwind in beautiful dog-friendly hotel rooms or suites. Make your stay extraordinary at Sheraton Grand Los Angeles.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d77798-Reviews-Sheraton_Grand_Los_Angeles-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "711 South Hope Street",
      street2: "",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90017-3803",
      address_string: "711 South Hope Street, Los Angeles, CA 90017-3803",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.047775",
    longitude: "-118.25814",
    timezone: "America/Los_Angeles",
    phone: "18446310595",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d77798-Sheraton_Grand_Los_Angeles-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#37 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "37",
    },
    rating: "4.5",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-66827-5.svg",
    num_reviews: "1565",
    review_rating_count: { 1: "42", 2: "33", 3: "90", 4: "377", 5: "1023" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "700",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d77798-m66827-Reviews-Sheraton_Grand_Los_Angeles-Los_Angeles_California.html#photos",
    price_level: "$$$",
    hours: { periods: [Array], weekday_text: [Array] },
    amenities: [
      "Pets Allowed",
      "Breakfast Available",
      "Wifi",
      "Meeting rooms",
      "Internet",
      "Suites",
      "Room service",
      "Free Internet",
      "Wheelchair access",
      "Restaurant",
      "Bar/Lounge",
      "Public Wifi",
      "Dry Cleaning",
      "Non-smoking rooms",
      "Fitness center",
      "Banquet Room",
      "Air conditioning",
      "Family Rooms",
      "Multilingual Staff",
      "Refrigerator in room",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Flatscreen TV",
      "Parking",
      "Facilities for Disabled Guests",
      "Housekeeping",
      "Bath / Shower",
      "Bottled Water",
      "Coffee / Tea Maker",
      "Desk",
      "English",
      "24-Hour Front Desk",
      "Hair Dryer",
      "Iron",
      "On-Demand Movies",
      "Paid Public Parking Nearby",
      "Seating Area",
      "24-Hour Security",
      "Secured Parking",
      "Shared Lounge / TV Area",
      "Spanish",
      "Taxi Service",
      "Telephone",
      "Wake Up Service / Alarm Clock",
      "Kids Stay Free",
      "Bowling Off-site",
      "Cable / Satellite TV",
      "Car Hire",
      "Express Check-in / Check-out",
      "Electric Kettle",
      "Executive Lounge Access",
      "Interconnected room(s) available",
      "Newspaper",
      "Patio",
      "Radio",
      "Shops",
      "Sofa",
      "Sofa Bed",
      "Valet Parking",
      "Vending Machine",
      "Walk-in Shower",
    ],
    parent_brand: "Marriott",
    brand: "Sheraton (Marriott Bonvoy)",
    category: { name: "hotel", localized_name: "Hotel" },
    subcategory: [[Object]],
    styles: ["Modern", "Value"],
    neighborhood_info: [[Object], [Object]],
    trip_types: [[Object], [Object], [Object], [Object], [Object]],
    awards: [[Object], [Object]],
  },
  {
    location_id: "78694",
    name: "Hilton Los Angeles / Universal City",
    description:
      "Experience this AAA 4 Diamond hotel, situated just a block away from the entrance to Universal Studios and minutes from Hollywood. The Hilton Los Angeles/Universal City hotel is perfect for travelers looking to explore some of Los Angeles' greatest attractions. All guest rooms and suites feature attractive decor and have high-speed internet access. Keep up-to-date with work at any time in the 24-hour business center. Have a Hollywood wedding in the 16,000 sq. ft. Sierra Ballroom, or hold conferences and meetings in the hotel's 32,000 sq. ft. of function space. Enjoy local cuisine in the Café Sierra hotel restaurant, which offers California, Continental and Chinese cuisine in a modern, brightly lit setting.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d78694-Reviews-Hilton_Los_Angeles_Universal_City-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "555 Universal Hollywood Drive",
      street2: "",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "91608-1001",
      address_string:
        "555 Universal Hollywood Drive, Los Angeles, CA 91608-1001",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.136444",
    longitude: "-118.35804",
    timezone: "America/Los_Angeles",
    phone: "18556050316",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d78694-Hilton_Los_Angeles_Universal_City-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#23 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "23",
    },
    rating: "4.0",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-66827-5.svg",
    num_reviews: "5986",
    review_rating_count: { 1: "241", 2: "291", 3: "773", 4: "1770", 5: "2911" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "2277",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d78694-m66827-Reviews-Hilton_Los_Angeles_Universal_City-Los_Angeles_California.html#photos",
    price_level: "$$$$",
    hours: { periods: [Array], weekday_text: [Array] },
    amenities: [
      "Shuttle Bus Service",
      "Pool",
      "Room service",
      "Internet",
      "Suites",
      "Wifi",
      "Paid Wifi",
      "Paid Internet",
      "Meeting rooms",
      "Non-smoking rooms",
      "Wheelchair access",
      "Concierge",
      "Restaurant",
      "Bar/Lounge",
      "Public Wifi",
      "Dry Cleaning",
      "Hot Tub",
      "Business center",
      "Fitness center",
      "Banquet Room",
      "Air conditioning",
      "Family Rooms",
      "Multilingual Staff",
      "Accessible rooms",
      "Refrigerator in room",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Heated pool",
      "Flatscreen TV",
      "Breakfast Buffet",
      "Poolside Bar",
      "Outdoor pool",
      "Parking",
      "Facilities for Disabled Guests",
      "Electric vehicle charging station",
      "ATM On Site",
      "Baggage Storage",
      "Breakfast in the Room",
      "Express Check-in / Check-out",
      "Coffee Shop",
      "Convenience Store",
      "Desk",
      "English",
      "Filipino",
      "Complimentary Instant Cofffee",
      "24-Hour Front Desk",
      "Gift Shop",
      "Interconnected room(s) available",
      "Iron",
      "Kids' Meals",
      "Kid-Friendly Buffet",
      "Newspaper",
      "On-Demand Movies",
      "Parking Garage",
      "Pool / Beach Towels",
      "Paid Private Parking On-site",
      "Paid Private Parking Nearby",
      "Seating Area",
      "24-Hour Security",
      "Shops",
      "Snack Bar",
      "Spanish",
      "Sun Loungers / Beach Chairs",
      "Taxi Service",
      "Valet Parking",
      "Wake Up Service / Alarm Clock",
      "Breakfast Available",
      "Chinese",
      "Vending Machine",
    ],
    parent_brand: "Hilton Worldwide",
    brand: "Hilton Hotels & Resorts",
    category: { name: "hotel", localized_name: "Hotel" },
    subcategory: [[Object]],
    styles: ["Park View", "Great View"],
    neighborhood_info: [[Object], [Object]],
    trip_types: [[Object], [Object], [Object], [Object], [Object]],
    awards: [[Object], [Object]],
  },
  {
    location_id: "8678267",
    name: "InterContinental Los Angeles Downtown",
    description:
      "As the tallest building west of Chicago, the InterContinental Los Angeles Downtown forever elevates the city skyline and is paired seamlessly with a genuinely personable commitment to service excellence second to none. Located in the epicenter of Downtown and mere blocks from Staples Center and L.A. Live, the hotel leads the way as the new architectural icon of luxury hospitality. Featuring a 70th floor sky lobby and 889 guest rooms including 109 suites, there is a myriad of culinary venues: La Boucherie, a Wine Spectator award-winning steakhouse; Dekkadance, an international market experience; and Spire 73 – the tallest open-air bar in the Western Hemisphere – located atop the 73rd floor. The hotel also offers 95,000 sq. ft. of indoor/outdoor meeting and event space, an outdoor pool, an executive-style gym with classes and steam rooms, and a signature Club InterContinental Lounge.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d8678267-Reviews-InterContinental_Los_Angeles_Downtown-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "900 Wilshire Blvd",
      street2: "Vehicle entry on 7th St. between Figueroa and Francisco",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90017-4701",
      address_string:
        "900 Wilshire Blvd Vehicle entry on 7th St. between Figueroa and Francisco, Los Angeles, CA 90017-4701",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.049725",
    longitude: "-118.26055",
    timezone: "America/Los_Angeles",
    phone: "18669783633",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d8678267-InterContinental_Los_Angeles_Downtown-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#84 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "84",
    },
    rating: "4.0",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-66827-5.svg",
    num_reviews: "1098",
    review_rating_count: { 1: "77", 2: "64", 3: "129", 4: "220", 5: "608" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "1778",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d8678267-m66827-Reviews-InterContinental_Los_Angeles_Downtown-Los_Angeles_California.html#photos",
    price_level: "$$$$",
    amenities: [
      "Pool",
      "Internet",
      "Suites",
      "Room service",
      "Free Internet",
      "Wheelchair access",
      "Restaurant",
      "Bar/Lounge",
      "Pets Allowed",
      "Wifi",
      "Public Wifi",
      "Free Wifi",
      "Dry Cleaning",
      "Meeting rooms",
      "Hot Tub",
      "Non-smoking rooms",
      "Fitness center",
      "Laundry Service",
      "Concierge",
      "Banquet Room",
      "Air conditioning",
      "Multilingual Staff",
      "Accessible rooms",
      "Minibar",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Rooftop Bar",
      "Heated pool",
      "Flatscreen TV",
      "Rooftop Terrace",
      "Breakfast Buffet",
      "Poolside Bar",
      "Outdoor pool",
      "Breakfast Available",
      "Parking",
      "Facilities for Disabled Guests",
      "Housekeeping",
      "Baggage Storage",
      "Bath / Shower",
      "Bathrobes",
      "Blackout Curtains",
      "Breakfast in the Room",
      "Coffee Shop",
      "Desk",
      "Fitness / Spa Locker Rooms",
      "Complimentary Toiletries",
      "24-Hour Front Desk",
      "Hair Dryer",
      "Iron",
      "Ironing Service",
      "Nightclub / DJ",
      "On-Demand Movies",
      "Parking Garage",
      "Pool / Beach Towels",
      "Pool with View",
      "Paid Private Parking On-site",
      "24-Hour Security",
      "Secured Parking",
      "Spanish",
      "Sun Loungers / Beach Chairs",
      "Valet Parking",
      "VIP Room Facilities",
      "Sauna",
      "Electric vehicle charging station",
      "Allergy-free Room",
      "ATM On Site",
      "Bowling Off-site",
      "Bridal Suite",
      "Cable / Satellite TV",
      "24-Hour Check-in",
      "Express Check-in / Check-out",
      "Children's Television Networks",
      "Clothes Rack",
      "Coffee / Tea Maker",
      "Complimentary Tea",
      "Currency Exchange",
      "English",
      "Executive Lounge Access",
      "Happy Hour",
      "Highchairs Available",
      "Interconnected room(s) available",
      "Kid-Friendly Buffet",
      "Landmark View",
      "Laptop Safe",
      "Mountain View",
      "Outdoor Dining Area",
      "Outdoor Fireplace",
      "Outdoor Furniture",
      "Patio",
      "Personal Trainer",
      "Paid Public Parking Nearby",
      "Seating Area",
      "Shallow End",
      "Snack Bar",
      "Soundproof Rooms",
      "Special Diet Menus",
      "Steam Room",
      "Sun Terrace",
      "Sun Umbrellas",
    ],
    parent_brand: "InterContinental",
    brand: "InterContinental",
    category: { name: "hotel", localized_name: "Hotel" },
    styles: ["Mountain View", "Luxury"],
    awards: [],
  },
];
