import AttractionCard from "./AttractionCard";
import { searchAttractions } from "@/app/_lib/data-service";
import yelpLogo from "@/public/imgs/yelp_logo.jpg";
import Image from "next/image";

async function FetchAttractions({ searchTerm, tripLocation, tripID }) {
  let attractions = [];
  if (searchTerm) {
    attractions = await searchAttractions(tripLocation, searchTerm);
  }

  return (
    <section className="flex flex-col">
      <h1 className="my-2 sm:text-xl text-center">
        RESULTS of SEARCH- Generated by Yelp:
      </h1>
      <figure className="sm:w-md sm:h-[50px] relative w-sm h-[30px] mb-4">
        <Image
          src={yelpLogo}
          fill
          className="object-contain"
          quality={100}
          placeholder="blur"
          alt="Yelp logo"
        />
      </figure>
      {attractions.length > 0 ? (
        <>
          {attractions.map((attraction, index) => {
            return (
              <AttractionCard
                attraction={attraction}
                index={index}
                key={attraction.location_id}
                tripID={tripID}
              />
            );
          })}{" "}
        </>
      ) : (
        <article className="p-3 flex flex-col gap-3 items-center text-theme-color-dark bg-gradient-white w-[100%] mx-auto rounded-sm shadow-md leading-6 text-md mt-4 sm:text-lg">
          <h2>
            No results to display. Either no search has been conducted yet or no
            results have come out of your search. If it is the latter, please
            refine your search and try again.
          </h2>
        </article>
      )}
    </section>
  );
}

export default FetchAttractions;
