const hotels = [
  {
    location_id: "23845025",
    name: "Conrad Los Angeles",
    description:
      "Daily Mandatory Charge includes: Destination Charge with premium internet access; daily $15 food and beverage credit; house car use; Conrad Spa dry sauna & tea blending bar; in-lobby premium coffee; RunGo app access for trails; PressReader. Mandatory Charge also includes CA & LA Tourism Assessments. Surrounded by iconic art, theatre, and music institutions, Conrad Los Angeles channels the bold originality, creative innovation and dynamic energy that fuels Downtown LA's newest cultural corridor. Heralded by the vision of legendary architect Frank Gehry, our hotel is an elegant destination for vibrant social events, remarkable gatherings and curated dining experiences by acclaimed chef and humanitarian Jose Andres. Here, framed by dramatic views of the Walt Disney Concert Hall and Downtown LA, discover energizing experiences that will ignite your inspiration.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d23845025-Reviews-Conrad_Los_Angeles-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "100 South Grand Ave.",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90012",
      address_string: "100 South Grand Ave., Los Angeles, CA 90012",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.055176",
    longitude: "-118.24858",
    timezone: "America/Los_Angeles",
    phone: "18556184701",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d23845025-Conrad_Los_Angeles-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#63 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "63",
    },
    rating: "4.5",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-66827-5.svg",
    num_reviews: "144",
    review_rating_count: { 1: "7", 2: "10", 3: "5", 4: "6", 5: "116" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "672",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d23845025-m66827-Reviews-Conrad_Los_Angeles-Los_Angeles_California.html#photos",
    price_level: "$$$$",
    amenities: [
      "Pool",
      "Internet",
      "Suites",
      "Room service",
      "Free Internet",
      "Wheelchair access",
      "Restaurant",
      "Spa",
      "Wifi",
      "Free Wifi",
      "Dry Cleaning",
      "Meeting rooms",
      "Non-smoking rooms",
      "Business center",
      "Fitness center",
      "Laundry Service",
      "Concierge",
      "Electric vehicle charging station",
      "English",
      "Pool with View",
      "Spanish",
      "Kids Activities",
      "Bar/Lounge",
      "Pets Allowed",
      "Banquet Room",
      "Air conditioning",
      "Accessible rooms",
      "Minibar",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Rooftop Pool",
      "Heated pool",
      "Flatscreen TV",
      "Rooftop Terrace",
      "Poolside Bar",
      "Outdoor pool",
      "Breakfast Available",
      "Facilities for Disabled Guests",
      "Housekeeping",
      "Sauna",
      "Baggage Storage",
      "Bathrobes",
      "Blackout Curtains",
      "Body Wrap",
      "Bottled Water",
      "Breakfast in the Room",
      "Cable / Satellite TV",
      "Children's Television Networks",
      "Clothes Rack",
      "Couples Massage",
      "Desk",
      "Facial Treatments",
      "Fitness Classes",
      "Fitness / Spa Locker Rooms",
      "Complimentary Toiletries",
      "24-Hour Front Desk",
      "Full Body Massage",
      "Hair Dryer",
      "Happy Hour",
      "Highchairs Available",
      "Iron",
      "Kids' Meals",
      "Landmark View",
      "Light Therapy",
      "Massage",
      "Mountain View",
      "Newspaper",
      "Outdoor Dining Area",
      "Outdoor Fireplace",
      "Outdoor Furniture",
      "Patio",
      "Pool / Beach Towels",
      "Pool View",
      "Private Bathrooms",
      "Paid Private Parking On-site",
      "Seating Area",
      "24-Hour Security",
      "Secured Parking",
      "Shoeshine",
      "Shops",
      "Sofa",
      "Steam Room",
      "Sun Deck",
      "Sun Loungers / Beach Chairs",
      "Sun Terrace",
      "Sun Umbrellas",
      "Telephone",
      "Valet Parking",
      "Wake Up Service / Alarm Clock",
      "Walk-in Shower",
      "Walking Tours",
      "Wardrobe / Closet",
      "Wine / Champagne",
      "Yoga Classes",
    ],
    parent_brand: "Hilton Worldwide",
    brand: "Conrad Hotels & Resorts",
    category: { name: "hotel", localized_name: "Hotel" },
    subcategory: [[Object]],
    styles: ["Luxury", "Romantic"],
    neighborhood_info: [],
    trip_types: [[Object], [Object], [Object], [Object], [Object]],
    awards: [[Object]],
  },
  {
    location_id: "77798",
    name: "Sheraton Grand Los Angeles",
    description:
      "Thrive brimming with style and substance at Sheraton Grand Los Angeles. Head to District Kitchen & Bar, our innovative on-site restaurant serving creative libations and farm-to-table cuisine. Work and play like a Los Angeleno at our fully equipped Sheraton Fitness center. If you are planning a professional meeting, special event, or a lavish wedding, ask about our indoor and outdoor event venues offering more than 35,000 square feet of space. After a busy day in DTLA, unwind in beautiful dog-friendly hotel rooms or suites. Make your stay extraordinary at Sheraton Grand Los Angeles.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d77798-Reviews-Sheraton_Grand_Los_Angeles-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "711 South Hope Street",
      street2: "",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90017-3803",
      address_string: "711 South Hope Street, Los Angeles, CA 90017-3803",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.047775",
    longitude: "-118.25814",
    timezone: "America/Los_Angeles",
    phone: "18446310595",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d77798-Sheraton_Grand_Los_Angeles-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#37 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "37",
    },
    rating: "4.5",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.5-66827-5.svg",
    num_reviews: "1565",
    review_rating_count: { 1: "42", 2: "33", 3: "90", 4: "377", 5: "1023" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "700",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d77798-m66827-Reviews-Sheraton_Grand_Los_Angeles-Los_Angeles_California.html#photos",
    price_level: "$$$",
    hours: { periods: [Array], weekday_text: [Array] },
    amenities: [
      "Pets Allowed",
      "Breakfast Available",
      "Wifi",
      "Meeting rooms",
      "Internet",
      "Suites",
      "Room service",
      "Free Internet",
      "Wheelchair access",
      "Restaurant",
      "Bar/Lounge",
      "Public Wifi",
      "Dry Cleaning",
      "Non-smoking rooms",
      "Fitness center",
      "Banquet Room",
      "Air conditioning",
      "Family Rooms",
      "Multilingual Staff",
      "Refrigerator in room",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Flatscreen TV",
      "Parking",
      "Facilities for Disabled Guests",
      "Housekeeping",
      "Bath / Shower",
      "Bottled Water",
      "Coffee / Tea Maker",
      "Desk",
      "English",
      "24-Hour Front Desk",
      "Hair Dryer",
      "Iron",
      "On-Demand Movies",
      "Paid Public Parking Nearby",
      "Seating Area",
      "24-Hour Security",
      "Secured Parking",
      "Shared Lounge / TV Area",
      "Spanish",
      "Taxi Service",
      "Telephone",
      "Wake Up Service / Alarm Clock",
      "Kids Stay Free",
      "Bowling Off-site",
      "Cable / Satellite TV",
      "Car Hire",
      "Express Check-in / Check-out",
      "Electric Kettle",
      "Executive Lounge Access",
      "Interconnected room(s) available",
      "Newspaper",
      "Patio",
      "Radio",
      "Shops",
      "Sofa",
      "Sofa Bed",
      "Valet Parking",
      "Vending Machine",
      "Walk-in Shower",
    ],
    parent_brand: "Marriott",
    brand: "Sheraton (Marriott Bonvoy)",
    category: { name: "hotel", localized_name: "Hotel" },
    subcategory: [[Object]],
    styles: ["Modern", "Value"],
    neighborhood_info: [[Object], [Object]],
    trip_types: [[Object], [Object], [Object], [Object], [Object]],
    awards: [[Object], [Object]],
  },
  {
    location_id: "78694",
    name: "Hilton Los Angeles / Universal City",
    description:
      "Experience this AAA 4 Diamond hotel, situated just a block away from the entrance to Universal Studios and minutes from Hollywood. The Hilton Los Angeles/Universal City hotel is perfect for travelers looking to explore some of Los Angeles' greatest attractions. All guest rooms and suites feature attractive decor and have high-speed internet access. Keep up-to-date with work at any time in the 24-hour business center. Have a Hollywood wedding in the 16,000 sq. ft. Sierra Ballroom, or hold conferences and meetings in the hotel's 32,000 sq. ft. of function space. Enjoy local cuisine in the Café Sierra hotel restaurant, which offers California, Continental and Chinese cuisine in a modern, brightly lit setting.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d78694-Reviews-Hilton_Los_Angeles_Universal_City-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "555 Universal Hollywood Drive",
      street2: "",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "91608-1001",
      address_string:
        "555 Universal Hollywood Drive, Los Angeles, CA 91608-1001",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.136444",
    longitude: "-118.35804",
    timezone: "America/Los_Angeles",
    phone: "18556050316",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d78694-Hilton_Los_Angeles_Universal_City-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#23 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "23",
    },
    rating: "4.0",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-66827-5.svg",
    num_reviews: "5986",
    review_rating_count: { 1: "241", 2: "291", 3: "773", 4: "1770", 5: "2911" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "2277",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d78694-m66827-Reviews-Hilton_Los_Angeles_Universal_City-Los_Angeles_California.html#photos",
    price_level: "$$$$",
    hours: { periods: [Array], weekday_text: [Array] },
    amenities: [
      "Shuttle Bus Service",
      "Pool",
      "Room service",
      "Internet",
      "Suites",
      "Wifi",
      "Paid Wifi",
      "Paid Internet",
      "Meeting rooms",
      "Non-smoking rooms",
      "Wheelchair access",
      "Concierge",
      "Restaurant",
      "Bar/Lounge",
      "Public Wifi",
      "Dry Cleaning",
      "Hot Tub",
      "Business center",
      "Fitness center",
      "Banquet Room",
      "Air conditioning",
      "Family Rooms",
      "Multilingual Staff",
      "Accessible rooms",
      "Refrigerator in room",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Heated pool",
      "Flatscreen TV",
      "Breakfast Buffet",
      "Poolside Bar",
      "Outdoor pool",
      "Parking",
      "Facilities for Disabled Guests",
      "Electric vehicle charging station",
      "ATM On Site",
      "Baggage Storage",
      "Breakfast in the Room",
      "Express Check-in / Check-out",
      "Coffee Shop",
      "Convenience Store",
      "Desk",
      "English",
      "Filipino",
      "Complimentary Instant Cofffee",
      "24-Hour Front Desk",
      "Gift Shop",
      "Interconnected room(s) available",
      "Iron",
      "Kids' Meals",
      "Kid-Friendly Buffet",
      "Newspaper",
      "On-Demand Movies",
      "Parking Garage",
      "Pool / Beach Towels",
      "Paid Private Parking On-site",
      "Paid Private Parking Nearby",
      "Seating Area",
      "24-Hour Security",
      "Shops",
      "Snack Bar",
      "Spanish",
      "Sun Loungers / Beach Chairs",
      "Taxi Service",
      "Valet Parking",
      "Wake Up Service / Alarm Clock",
      "Breakfast Available",
      "Chinese",
      "Vending Machine",
    ],
    parent_brand: "Hilton Worldwide",
    brand: "Hilton Hotels & Resorts",
    category: { name: "hotel", localized_name: "Hotel" },
    subcategory: [[Object]],
    styles: ["Park View", "Great View"],
    neighborhood_info: [[Object], [Object]],
    trip_types: [[Object], [Object], [Object], [Object], [Object]],
    awards: [[Object], [Object]],
  },
  {
    location_id: "8678267",
    name: "InterContinental Los Angeles Downtown",
    description:
      "As the tallest building west of Chicago, the InterContinental Los Angeles Downtown forever elevates the city skyline and is paired seamlessly with a genuinely personable commitment to service excellence second to none. Located in the epicenter of Downtown and mere blocks from Staples Center and L.A. Live, the hotel leads the way as the new architectural icon of luxury hospitality. Featuring a 70th floor sky lobby and 889 guest rooms including 109 suites, there is a myriad of culinary venues: La Boucherie, a Wine Spectator award-winning steakhouse; Dekkadance, an international market experience; and Spire 73 – the tallest open-air bar in the Western Hemisphere – located atop the 73rd floor. The hotel also offers 95,000 sq. ft. of indoor/outdoor meeting and event space, an outdoor pool, an executive-style gym with classes and steam rooms, and a signature Club InterContinental Lounge.",
    web_url:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d8678267-Reviews-InterContinental_Los_Angeles_Downtown-Los_Angeles_California.html?m=66827",
    address_obj: {
      street1: "900 Wilshire Blvd",
      street2: "Vehicle entry on 7th St. between Figueroa and Francisco",
      city: "Los Angeles",
      state: "California",
      country: "United States",
      postalcode: "90017-4701",
      address_string:
        "900 Wilshire Blvd Vehicle entry on 7th St. between Figueroa and Francisco, Los Angeles, CA 90017-4701",
    },
    ancestors: [[Object], [Object], [Object]],
    latitude: "34.049725",
    longitude: "-118.26055",
    timezone: "America/Los_Angeles",
    phone: "18669783633",
    write_review:
      "https://www.tripadvisor.com/UserReview-g32655-d8678267-InterContinental_Los_Angeles_Downtown-Los_Angeles_California.html?m=66827",
    ranking_data: {
      geo_location_id: "32655",
      ranking_string: "#84 of 425 hotels in Los Angeles",
      geo_location_name: "Los Angeles",
      ranking_out_of: "425",
      ranking: "84",
    },
    rating: "4.0",
    rating_image_url:
      "https://www.tripadvisor.com/img/cdsi/img2/ratings/traveler/4.0-66827-5.svg",
    num_reviews: "1098",
    review_rating_count: { 1: "77", 2: "64", 3: "129", 4: "220", 5: "608" },
    subratings: {
      0: [Object],
      1: [Object],
      2: [Object],
      3: [Object],
      4: [Object],
      5: [Object],
    },
    photo_count: "1778",
    see_all_photos:
      "https://www.tripadvisor.com/Hotel_Review-g32655-d8678267-m66827-Reviews-InterContinental_Los_Angeles_Downtown-Los_Angeles_California.html#photos",
    price_level: "$$$$",
    amenities: [
      "Pool",
      "Internet",
      "Suites",
      "Room service",
      "Free Internet",
      "Wheelchair access",
      "Restaurant",
      "Bar/Lounge",
      "Pets Allowed",
      "Wifi",
      "Public Wifi",
      "Free Wifi",
      "Dry Cleaning",
      "Meeting rooms",
      "Hot Tub",
      "Non-smoking rooms",
      "Fitness center",
      "Laundry Service",
      "Concierge",
      "Banquet Room",
      "Air conditioning",
      "Multilingual Staff",
      "Accessible rooms",
      "Minibar",
      "Conference Facilities",
      "Non-smoking hotel",
      "Safe",
      "Rooftop Bar",
      "Heated pool",
      "Flatscreen TV",
      "Rooftop Terrace",
      "Breakfast Buffet",
      "Poolside Bar",
      "Outdoor pool",
      "Breakfast Available",
      "Parking",
      "Facilities for Disabled Guests",
      "Housekeeping",
      "Baggage Storage",
      "Bath / Shower",
      "Bathrobes",
      "Blackout Curtains",
      "Breakfast in the Room",
      "Coffee Shop",
      "Desk",
      "Fitness / Spa Locker Rooms",
      "Complimentary Toiletries",
      "24-Hour Front Desk",
      "Hair Dryer",
      "Iron",
      "Ironing Service",
      "Nightclub / DJ",
      "On-Demand Movies",
      "Parking Garage",
      "Pool / Beach Towels",
      "Pool with View",
      "Paid Private Parking On-site",
      "24-Hour Security",
      "Secured Parking",
      "Spanish",
      "Sun Loungers / Beach Chairs",
      "Valet Parking",
      "VIP Room Facilities",
      "Sauna",
      "Electric vehicle charging station",
      "Allergy-free Room",
      "ATM On Site",
      "Bowling Off-site",
      "Bridal Suite",
      "Cable / Satellite TV",
      "24-Hour Check-in",
      "Express Check-in / Check-out",
      "Children's Television Networks",
      "Clothes Rack",
      "Coffee / Tea Maker",
      "Complimentary Tea",
      "Currency Exchange",
      "English",
      "Executive Lounge Access",
      "Happy Hour",
      "Highchairs Available",
      "Interconnected room(s) available",
      "Kid-Friendly Buffet",
      "Landmark View",
      "Laptop Safe",
      "Mountain View",
      "Outdoor Dining Area",
      "Outdoor Fireplace",
      "Outdoor Furniture",
      "Patio",
      "Personal Trainer",
      "Paid Public Parking Nearby",
      "Seating Area",
      "Shallow End",
      "Snack Bar",
      "Soundproof Rooms",
      "Special Diet Menus",
      "Steam Room",
      "Sun Terrace",
      "Sun Umbrellas",
    ],
    parent_brand: "InterContinental",
    brand: "InterContinental",
    category: { name: "hotel", localized_name: "Hotel" },
    styles: ["Mountain View", "Luxury"],
    awards: [],
  },
];

//base hotel data ready to be formatted

import fetchLocationDetails from "@/app/_lib/fetch-attraction-and-hotel-details";
import HotelCard from "./HotelCard";

async function FetchHotels() {
  //ANTICPATED FETCH FUNCTION FOR HOTELS.
  // const location = encodeURIComponent("Los Angeles, CA".trim()); //will change later

  // const url = `https://api.content.tripadvisor.com/api/v1/location/search?key=${process.env.TRIP_ADVISOR_KEY}&searchQuery=${location}&category=hotels`;

  // const options = { method: "GET", headers: { accept: "application/json" } };
  // const res = await fetch(url, options);
  // const hotels = await res.json();
  // const hotelIDs = hotels.map((hotel) => hotel.location_id);
  // const hotelDataArr = await fetchLocationDetails(hotelIDs);

  return (
    <section>
      <h1 className="my-2 text-center">RESULTS of SEARCH:</h1>
      {hotels.map((hotel, index) => (
        <HotelCard hotel={hotel} index={index} key={hotel.location_id} />
      ))}
    </section>
  );
}

export default FetchHotels;
